config/routes.rb
ExampleStore::Application.routes.draw do

  #
  # Shoppe admin interface
  #
  mount Notices::Engine => "/notices"
  
  #
  # Product browising
  #
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
  
  #
  # Order status
  #
  get 'order/:token' => 'orders#status', :as => 'order_status'

  #
  # Basket
  #
  get 'basket' => 'orders#show', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
  #
  # Checkout
  #
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
  #
  # Static pages
  #
  get ':action', :controller => 'pages', :as => 'page'
 
  delete 'logout' => 'notices/sessions#destroy'

  # 
  # Homepage
  #
  root :to => 'pages#home'
  
end

Notices::Engine.routes.draw do

  get 'attachment/:id/:filename.:extension' => 'attachments#show'
  resources :product_categories
  resources :products do
    resources :variants
  end
  resources :orders do
    post :search, :on => :collection
    post :accept, :on => :member
    post :reject, :on => :member
    post :ship, :on => :member
    get :despatch_note, :on => :member
    resources :payments, :only => [:create, :destroy] do
      match :refund, :on => :member, :via => [:get, :post]
    end
  end
  resources :stock_level_adjustments, :only => [:index, :create]
  resources :delivery_services do
    resources :delivery_service_prices
  end
  resources :tax_rates
  resources :users
  resources :countries
  resources :attachments, :only => :destroy

  get 'settings'=> 'settings#edit'
  post 'settings' => 'settings#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  match 'login/reset' => 'sessions#reset', :via => [:get, :post]

  delete 'logout' => 'sessions#destroy'
  root :to => 'dashboard#home'

end

app/views/shared/_basket.html.haml
.basket
  - if has_order? && current_order.has_items?
    %p.quantity you have subscribed to <b>#{pluralize current_order.total_items, 'notice(s)'}</b>

    %p.buttons
      = link_to "View Subscribed Notices", basket_path
     

  - else
    %p.empty <b>You have not subscribed to any notices.</b>

app/views/shared/_order_items.html.haml
%table.orderItems
  %thead
    %tr
      %td Name
      %td Short Description
      %td Price
      %td Posted By
      %td Posted On
      %td Unsubscribe
  %tbody
    - for item in order.order_items.includes(:ordered_item, :order)
      %tr
        %td= item.ordered_item.name
        %td= item.ordered_item.short_description
        %td.money.price= number_to_currency item.unit_price
        %td= item.order.first_name
        %td= item.order.created_at
        %td=  link_to "Unsubscribe", remove_basket_item_path(item), :method => :delete
        
  

app/views/shared/_product_list.html.haml
%ul.products
  - for product in products.includes(:default_image, :product_category)
    %li
      .img{:style => product.default_image ? "background-image:url(#{product.default_image.path})" : ''}
      %h4= product.name
      %h6= product.product_category.name
      %p.info= truncate product.short_description, :length => 90
      %p.buttons 
        = link_to "Read More", product_path(product.product_category.permalink, product.permalink)
        - if product.orderable?
          = link_to "Subscribe", buy_product_path(product.product_category.permalink, product.permalink), :class => 'add', :method => :post
      %p.price= number_to_currency product.price
      