config/routes.rb
ExampleStore::Application.routes.draw do

  #
  # Shoppe admin interface
  #
  mount Notices::Engine => "/notices"
  
  #
  # Product browising
  #
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
  
  #
  # Order status
  #
  get 'order/:token' => 'orders#status', :as => 'order_status'

  #
  # Basket
  #
  get 'basket' => 'orders#show', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
  #
  # Checkout
  #
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
  #
  # Static pages
  #
  get ':action', :controller => 'pages', :as => 'page'
 
  delete 'logout' => 'notices/sessions#destroy'

  # 
  # Homepage
  #
  root :to => 'pages#home'
  
end

Notices::Engine.routes.draw do

  get 'attachment/:id/:filename.:extension' => 'attachments#show'
  resources :product_categories
  resources :products do
    resources :variants
  end
  resources :orders do
    post :search, :on => :collection
    post :accept, :on => :member
    post :reject, :on => :member
    post :ship, :on => :member
    get :despatch_note, :on => :member
    resources :payments, :only => [:create, :destroy] do
      match :refund, :on => :member, :via => [:get, :post]
    end
  end
  resources :stock_level_adjustments, :only => [:index, :create]
  resources :delivery_services do
    resources :delivery_service_prices
  end
  resources :tax_rates
  resources :users
  resources :countries
  resources :attachments, :only => :destroy

  get 'settings'=> 'settings#edit'
  post 'settings' => 'settings#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  match 'login/reset' => 'sessions#reset', :via => [:get, :post]

  delete 'logout' => 'sessions#destroy'
  root :to => 'dashboard#home'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{@page_title} to BU NoticeIt
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    = yield :head
  %body
    


    = display_flash

    / The main header displayed on all pages
    / Sometimes will be shorted as the page content dictates. 
    %header.main{:class => @full_header ? 'full' : 'basic'}
      .inner
        / Primary navigation
        %nav.main

        

          %h2
          %p.intro


    
    / Main content section
    %section.content
      .inner
        %nav1.main
          %ul
            %li= link_to "Home", root_path, :nav_item => :home
            %li
              = link_to "Categories", catalogue_path, :nav_item => :catalogue, :class => 'noborder'
              %ul
                - for category in Notices::ProductCategory.ordered
                  %li= link_to category.name, products_path(category.permalink)
              %li= link_to "Add Notice", "notices/products/new"
              %li= link_to "View my Notices", "notices/products"
              %li= link_to "Logout", :logout, :method => :delete



        / Sidebar
        %section.sidebar
          - if content_for?(:sidebar)
            = yield :sidebar
          - else
            = render 'shared/basket'
            = render 'shared/reasons'
      
        / Primary section
        %section.primary
          = yield
      
    / Footer
    %footer.main
      .inner

        / Useful footer links (policies etc...)